config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :interpreters
  namespace :interpreters do
    root to: 'dashboard#index'
  end

  devise_for :users
  namespace :users do
    root to: 'dashboard#index'
  end

  resources :cotations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cotation.rb
class Cotation < ApplicationRecord
end

app/models/interpreter.rb
class Interpreter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    interpreters_root_path
  end

  def after_sign_out_path_for(resource)
    new_interpreter_session_path
  end

  protected
  def layout_by_resource
    return "layouts/session" if devise_controller?

    "layouts/application"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/interpreters/app_interpreter_controller.rb
class Teachers::AppTeacherController < ApplicationController
  layout 'interpreters/layouts/application'

  before_action :authenticate_interpreter!
end

app/controllers/interpreters/dashboard_controller.rb
class Interpreters::DashboardController < interpreters::AppInterpreterController
  def index
  end
end

app/controllers/users/app_user_controller.rb
class Users::AppUserController < ApplicationController
  layout 'users/layouts/application'

  before_action :authenticate_user!
end

app/controllers/users/cotations_controller.rb
class CotationsController < ApplicationController
  def index
    @cotations = Cotation.all
  end

  def show
    @cotation = Cotation.find(params[:id])
  end

  def new
  end

  def create
    @cotation = Cotation.new(cotation_params)
    @cotation.save
    redirect_to @cotation
  end

  private
  def cotation_params
    params.require(:cotation).permit(:type, :quantity)
  end

end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
      notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
    end

  def bootstrap_icon_for(flash_type)
      { success: 'ok-circle', error: 'remove-circle', alert: 'warning-sign',
        notice: 'exclamation-sign' }[flash_type] || 'question-sign'
  end

  def full_title(page_title = '', base_title = 'PHew')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/cotations_helper.rb
module CotationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interpreters/dashboard_helper.rb
module Interpreters::DashboardHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/cotations/index.html.erb
<h1>Mostrando Cotações</h1>

<table>

  <% @cotations.each do |cotation| %>
    <tr>
      <td><%= cotation.type %></td>
      <td><%= cotation.quantity %></td>
      <td><%= link_to 'Mostrar', cotation_path(cotation) %></td>
    </tr>
  <% end %>
</table>

app/views/cotations/new.html.erb
<% provide(:head_title, "Fazer Cotação") %>
<h2>Solicitar Cotação</h2>

<%= simple_form_for :cotation, url: cotations_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Tipo %>
    <%= f.input :Quantidade_de_Palavras %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Solicitar" %>
  </div>
<% end %>

app/views/cotations/show.html.erb
<% provide(:head_title, "Cotação Solicitada") %>

<%= simple_form_for :cotation, url: cotations_path do |f| %>
  <%= f.error_notification %>


<h2>Cotação Solicitada!</h2>

  <div class="form-inputs">
    <p>
      <strong>Tipo:</strong>
      <%= @cotation.type %>
    </p>

    <p>
      <strong>Quantidade de Palavras:</strong>
      <%= @cotation.quantity %>
    </p>
  </div>
<%= link_to "Voltar", :back %>
<% end %>

app/views/home/index.html.erb
<h3>PHew Traduções e Adaptações</h3>
<p>Faça uma cotação!</p>

app/views/interpreters/dashboard/index.html.erb
<h1>Interpreters::Dashboard#index</h1>
<p>Find me in app/views/interpreters/dashboard/index.html.erb</p>

app/views/interpreters/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
      data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(interpreters_root_path, class: "navbar-brand") do %>
        PHew
      <% end %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_interpreter.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                Meu perfil
              <% end %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to(destroy_interpreter_session_path, method: :delete) do %>
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                Sair
              <% end %>
            </li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/interpreters/layouts/_sidebar.html.erb
<div id="sidebar-default-parent">
  <ul id="sidebar-menu">

    <li>
      <%= link_to "Página inicial", interpreters_root_path, title: "Página inicial" %>
    </li>

  </ul>
</div>

app/views/interpreters/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:head_title)) %></title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'interpreters/application',
            media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'interpreters/application',
            'data-turbolinks-track': 'reload' %>
    </head>

    <body>

      <div id="page-header">
           <%= render 'interpreters/layouts/navbar'%>
      </div> <!-- page-header -->


      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
            <%= render 'interpreters/layouts/sidebar' %>
          </div> <!-- sidebar -->

          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <section id="<%= controller_name %>-<%= action_name %>" >

              <%= render 'shared/flash_messages'%>

              <header class="page-header">
                <h1><%= yield(:title) %></h1>
              </header>

              <%= yield %>

            </section>
          </div> <!-- page-content -->
        </div> <!-- row -->
      </div> <!-- container-fluid -->

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:head_title)) %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all',
  'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <p class="alert"><%= alert %></p>

  <div id="home-index" class="container">
    <div class="horizontal-centering">


      <%= render 'shared/flash_messages'%>


    </div> <!-- .vertical-centering .horizontal-centering -->
    <%= yield %>
  </div> <!-- #home-index -->

</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
   <head>
       <title><%= full_title(yield(:head_title)) %></title>
       <%= csrf_meta_tags %>

       <%= stylesheet_link_tag    'session', media: 'all',
                                  'data-turbolinks-track': 'reload' %>
       <%= javascript_include_tag 'session',
                                    'data-turbolinks-track': 'reload' %>
   </head>

   <body>

     <div id="<%= controller_name %>-<%= action_name %>" class="container">
       <div class="vertical-centering horizontal-centering">

          <%= render 'shared/flash_messages'%>

          <div>
               <h3 class="text-center gray-text2"><%= yield :title %></h3>
               <p class="gray-text2"><%= yield :sub_title %></p>
          </div>

          <%= yield %>

       </div> <!-- .vertical-centering .horizontal-centering -->
     </div> <!-- #home-index -->

   </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <i class="glyphicon glyphicon-<%= bootstrap_icon_for(type) %>"></i>
    <%= message %>
  </div>
<% end %>

app/views/users/dashboard/index.html.erb
<h1>Users::Dashboard#index</h1>
<p>Find me in app/views/users/dashboard/index.html.erb</p>